[package]
name = "new_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.12"
clap = { version = "4.5.45", features = ["derive"]}
slotmap = "1.0.7"
strum = "0.27.2"
strum_macros = "0.27.2"
trie-rs = "0.4.2"

[profile.dev]
opt-level = 0
debug = true